[profile.default]
src = "src"
out = "out"
libs = ["lib", "node_modules"]
solc = "0.8.13"
test = "test"
script = "script"
broadcast = "broadcast"
optimizer = true
optimizer_runs = 500
ffi = true
remappings = [
  '@openzeppelin/contracts/=lib/openzeppelin-contracts/lib/openzeppelin-contracts/contracts/',
]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[fuzz]
runs = 1000

[invariant]
runs = 1000
depth = 128
fail_on_revert = false

